version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - GITHUB_ID
      - GITHUB_SECRET
      - GOOGLE_API_KEY
      - OPENAI_API_KEY
      - GITHUB_TOKEN
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    restart: always
